<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AjuanBansosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Sample data
        $data = [
            [
                'id_kartuKeluarga' => 2,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 3,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 4,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '5',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '40m - 60m',
                'pengeluaran_listrik' => '50.000 - 100.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Tambahkan lebih banyak data sampel sesuai kebutuhan
            [
                'id_kartuKeluarga' => 2,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '<20m',
                'pengeluaran_listrik' => '>300.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 3,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '5',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 4,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '2',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '40m - 60m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 5,
                'status_rumah' => 'Milik Sendiri',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 6,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 7,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '3.000.000 - 4.000.000',
                'luas_tempat_tinggal' => '40m - 60m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 8,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '3.000.000 - 4.000.000',
                'luas_tempat_tinggal' => '40m - 60m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 9,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '>5',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '<50.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 10,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '1',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '<50.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 11,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '2',
                'penghasilan_keluarga' => '>5.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '>300.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'ditolak',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 12,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '>5',
                'penghasilan_keluarga' => '2.000.000 - 3.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '<50.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 13,
                'status_rumah' => 'Kontrak/kos',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '50.000 - 100.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 14,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '1',
                'penghasilan_keluarga' => '2.000.000 - 3.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '50.000 - 100.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 15,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '4',
                'penghasilan_keluarga' => '3.000.000 - 4.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '50.000 - 100.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 16,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '1',
                'penghasilan_keluarga' => '2.000.000 - 3.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '200.000 - 300.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'ditolak',
                'created_at' => '2023-10-12 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 2,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-11-30 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 3,
                'status_rumah' => 'Milik sendiri',
                'tanggungan' => '5',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'ditolak',
                'created_at' => '2023-11-30 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 4,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '2',
                'penghasilan_keluarga' => '1.000.000 - 2.000.000',
                'luas_tempat_tinggal' => '40m - 60m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diterima',
                'created_at' => '2023-11-30 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 5,
                'status_rumah' => 'Milik Sendiri',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '60m - 80m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'ditolak',
                'created_at' => '2023-11-30 12:00:00',
                'updated_at' => Carbon::now(),
            ],
            [
                'id_kartuKeluarga' => 6,
                'status_rumah' => 'Tinggal dengan keluarga',
                'tanggungan' => '3',
                'penghasilan_keluarga' => '<1.000.000',
                'luas_tempat_tinggal' => '20m - 40m',
                'pengeluaran_listrik' => '100.000 - 200.000',
                'foto_rumah' => 'contoh-foto-rumah.jpg',
                'SKTM' => 'contoh-sktm.jpg',
                'status' => 'diproses',
                'created_at' => '2023-11-30 12:00:00',
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert data into the table
        DB::table('tb_ajuan_bansos')->insert($data);
        ;
    }
}